id: sync_from_git
namespace: prod

tasks:
  - id: git
    type: io.kestra.plugin.git.SyncFlows
    url: https://github.com/centaurin/carica-kestra
    branch: main
    targetNamespace: prod
    username: kbnopro
    password: "{{ envs.github_token }}"
    dryRun: true

triggers:
  - id: github_webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ envs.webhook_key }}"